### PR TITLE
setup typedoc

### PR DESCRIPTION
**Pull request by vuvoth**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Create docs folders.  
image
 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vimwitch** [comment]
This looks good but can we put docs on pause until we finish the features? We want to freeze the app in late august, after that would be a good time to update the docs, because nothing should change.

**Comment by vuvoth** [comment]
> This looks good but can we put docs on pause until we finish the features? We want to freeze the app in late august, after that would be a good time to update the docs, because nothing should change.

This setup is independence. Typedoc uses a comments in source code to gen the API docs.

**Comment by vimwitch** [comment]
Yea but I think we should have a discussion of "do we want to use inline comments to create documentation". There are other ways to do it that we should consider and I'd rather do it once later than do it now and undo it later.

**Comment by vuvoth** [comment]
> Yea but I think we should have a discussion of "do we want to use inline comments to create documentation". There are other ways to do it that we should consider and I'd rather do it once later than do it now and undo it later.

Thanks! Make sense 👍🏼

**Pull request closed without merging**
