### PR TITLE
chore: Importing @types/snarkjs

### PR DESCRIPTION
**Pull request by FoodChain1028**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`yarn build`) was run locally in root directory and any changes were pushed
- [X] Lint (`yarn lint:fix`) was run locally in root directory and any changes were pushed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [X] Other (please describe): importing the defined types in `@types/snarkjs`

## What is the current behavior?

Issue Number: #548 

## What is the new behavior?

- There are two attributes, curve and protocol in Groth16Proof. 

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by vivianjeng — COMMENTED** [review]
It looks good to me.
Could you merge the `main` branch please? 🙏🏻

**Comment by FoodChain1028** [comment]
> It looks good to me. Could you merge the `main` branch please? 🙏🏻

Yes! Thanks. But I have a question when merging `BaseProof.ts`.
I deleted the SnarkProof in `@unirep/utilis` and replaced with `Groth16Proof` in `@types/snarkjs`. 

The function doc should be modified.
```ts
  /**
     * The proof data in [`SnarkProof`](https://developer.unirep.io/docs/utils-api/interfaces/SnarkProof.md) format. Use this when manually verifying with `snarkjs`.
     */
    readonly _snarkProof: Groth16Proof
    /**
     * The string name of the type of circuit this proof came from. For the `BaseProof` class this is undefined.
     */
```

Should I just leave a TODO comment here to make this be modified in the future?

**Comment by vivianjeng** [comment]
> Should I just leave a TODO comment here to make this be modified in the future?

@FoodChain1028 Feel free to modify this sentence
e.g. you can just change the type and the doc link in the `BaseProof.ts`
```
/**
 * The proof data in [`Groth16Proof`](may the link to @types/snarkjs) ...
 */
```

The doc `SnarkProof.md` is auto generated so it will be deleted in the next version if there is no `SnarkProof` exported from `@unirep/utils`

**Comment by FoodChain1028** [comment]
Hi, @vivianjeng  I've complete merging! thank you for reviewing

**Review by vivianjeng — APPROVED** [review]
LGTM
Thank you

**Pull request merged**
