### PR TITLE
471 rename proof verifiers

### LINKED ISSUE #471: Rename `proofVerifiers` to `verifierHelpers`
In #427 we add helper contracts to decode control signals and check roots/other values. This contracts are called `proofVerifiers`, and they call into `verifiers`. These terms are confusing, instead we could call `proofVerifiers`, `verifierHelpers`. e.g. a `verifierHelper` verifies the proof _and_ decodes the `publicSignals`.

Open to other ideas too, `proofVerifiers` is just confusing to me

### PR DESCRIPTION
**Pull request by chndr1**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally in root directory and any changes were pushed
- [x] Lint (`yarn lint:fix`) was run locally in root directory and any changes were pushed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
The contracts used to decode key signals and verify them are called `proofVerifiers`, which is confusing.

Closes #471 

## What is the new behavior?
`proofVerifiers` are now called `verifyHelpers`.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Related to issue #427  which describes the separation of the verification functions from the main Unirep contract. Updated documentation pertaining to `deployVerifierHelper` (prev. `deployProofVerifier`) will be added in #472 and #473

### CODE REVIEW

**Comment by chndr1** [comment]
#427 is a dependency. Would like for my rebase to be checked before I close it 🙃

**Review by vivianjeng — CHANGES_REQUESTED** [review]
you have to also remove the `proofVerifiers`?
and remove the original document of proof verifiers?

**Comment by vimwitch** [comment]
Definitely rebase this branch onto `main`

**Comment by vimwitch** [comment]
This branch still has lots of duplicate commits. It looks like only commits [a0ebf00](https://github.com/Unirep/Unirep/pull/476/commits/a0ebf0011347b5f2337b18a0df027c690f98c33a) to [a3241e7](https://github.com/Unirep/Unirep/pull/476/commits/a3241e7cfe643d8c394994b42133aa69c3f9ef6c) are specific to this PR.

You could rebase this onto main, or you could take the new commits and cherry pick them onto a branch made from main. Note that merging is _not_ the same as rebasing, [this](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) article has a good visualization. The [git docs](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) have a much more detailed explanation.

In this case you're probably better off [cherry-picking](https://www.atlassian.com/git/tutorials/cherry-pick) the changes onto a new branch.

You can do this like

```bash
git checkout main
git pull
git checkout -b 471-proof-helpers
git cherry-pick 1b60a46^..a3241e7
# The above command will apply commits 1b60a46 to a3241 onto the current branch
```

Note that in the current version history commits 1b60a46 to a3241e7 are duplicated, but separated by merge commits, and preceded by the (unsquashed) history of the `main` branch. All of this should be discarded just leaving the commits applying new changes.

**Review by vivianjeng — APPROVED** [review]

**Review by vimwitch — APPROVED** [review]

**Pull request merged**
