### PR TITLE
feat(utils): use `@semaphore-protocol/identity`

### PR DESCRIPTION
**Pull request by vivianjeng**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

There is no `secretHash` provided in `@semaphore-protocol/identity`: https://github.com/semaphore-protocol/semaphore/blob/main/packages/identity/src/identity.ts

I think we should either
1. write a inherent class from `@semaphore-protocol/identity` in `@unirep/utils`
2. change circuit to take inputs of `trapdoor` and `nullifier` (but the constraints will increase)
3. write hash([id.trapdoor, id.nullifier]) in each circuit input

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by vimwitch — APPROVED** [review]
LGTM, once semaphore-protocol/semaphore#294 is done we can remove our subclass

**Comment by vimwitch** [comment]
Oh make sure to update the docs `utils-api/identity.md`

**Review by vimwitch — CHANGES_REQUESTED** [review]
Needs docs update

**Comment by vivianjeng** [comment]
> Needs docs update

It's already updated in `docs/docs/utils-api/identity.md`
I think the versioned one shouldn't be updated because it is published with no @semaphore-protocol/identity changes

Is there anything missing?

**Comment by vimwitch** [comment]
Ah i missed that. So the semaphore team just pushed `@semaphore-protocol/identity@3.5.0` which includes a property `secret` on the `Identity` class. We can use this version and avoid subclassing ourselves to add the `secretHash`

**Review by vimwitch — APPROVED** [review]

**Pull request merged**
