### PR TITLE
Get started

### LINKED ISSUE #371: docs: add "Getting Started" section
The "Getting Started" section aims to provide a brief introduction to Unirep and to guide developers through the process of using `create-unirep-app`. 

This section should include a step-by-step tutorial, which covers the installation of `create-unirep-app` and important functionality of the repository. Additionally, the tutorial should explain how Unirep works to help developers understand the system better.

Examples of attesters can be a separate section with comments on how the example attester is using the unirep functionality.

### PR DESCRIPTION
**Pull request by vivianjeng**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: close #371 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AnthonyMadia** [comment]
Latest commit fixes grammar, typos, and syntax while adding information and an image about the architecture of create-unirep-app.

Aside from that, I thought the explanation of the Provable and Claim data might not be clear, so I added some additional context there.

We may also want to include assumptions we make about the relay being a point of centralization/tx censorship in the Create-Unirep-App Architecture section.

**Comment by vimwitch** [comment]
Fixed some typos and moved the images to the local repo. lgtm

**Comment by vivianjeng** [comment]
@vimwitch @CJ-Rose I updated the verify proof sections
mainly in this commit [f2c46fa](https://github.com/Unirep/Unirep/pull/441/commits/f2c46fa2f35d0a18010e6a19e97ac77404222271)
please help me check if everything is okay 🙏🏻

**Review by CJ-Rose — APPROVED** [review]
lgtm!

**Review by vimwitch — APPROVED** [review]

**Pull request merged**
