### PR TITLE
V1.1 test

### PR DESCRIPTION
**Pull request by vivianjeng**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- add `synchronizer.test.ts`, `userState.test.ts`
- merge `v1.0.1`
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by vimwitch** [comment]
This pr brings in some changes from the `v1` branch (most notably #140 and #145). The `v1` and `v1.1` branches have diverged enough that I think it's better to just redo those changes manually.

**Comment by vivianjeng** [comment]
Since I already merged `v1.0.1` in this PR
I think we don't have to do it manually again

**Comment by vimwitch** [comment]
The problem is this pr has _a lot_ of diffs and a super unclear commit history. I intended the `v1` and `v1.1` branches to have separate histories. In `v1` we just fix any bugs that might appear, then we do active development on `v1.1` (main). Can you break this pr into smaller pieces?

**Comment by vivianjeng** [comment]
it is okay to keep `v1` and `v1.1` in different branches but we should include the changes in `v1.1`
yeah I think when `v1.1-graffiti` and `v1.0.1` are merged it will be more clear

**Pull request closed without merging**
