### PR TITLE
Crypto backward compat

### PR DESCRIPTION
**Pull request by vimwitch**
Refactor accessor functions in `ZkIdentity` for backward compatibility.

### CODE REVIEW

**Comment by vimwitch** [comment]
depends #32

**Comment by vivianjeng** [comment]
I am trying to use the [`@zk-kit/identity`](https://github.com/privacy-scaling-explorations/zk-kit/tree/main/packages/identity)
but since the sha256 package they used is outdated (and npm hasn't updated yet), I still rewrite it in `@unirep/crypto`.
will I ask them to update npm package?

**Comment by vimwitch** [comment]
@vivianjeng Yea i think it's a good idea. It would be nice if they used getters like in this PR. Functions like `getNullifier()` make it seems like some calculation is happening when really it's just a variable being read.

**Review by vivianjeng — APPROVED** [review]
Yeah I am convinced
we can keep getters in `@unirep/crypto` and wait zk-kit updated

**Pull request merged**
