### PR TITLE
[circuit] proves an epoch key and graffiti pre-image only 

### PR DESCRIPTION
**Pull request by yuriko627**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- adding a circuit that only proves the graffiti 
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vivianjeng** [comment]
Actually I prefer this to be in unirep-social only
we can prove a lot of things in one circuit: epoch key, graffiti, minRep, state tree root...
but if we separate all these things into different circuit
1. epoch key + graffiti
2. epoch key + minRep
3. graffiti + minRep + state tree root
...
we will have many combinations 
It is not only hard for users to choose which proof to use but also we will have to deploy all these verifiers on-chain

**Comment by yuriko627** [comment]
So should I move this circuit file to Unirep Social repo?

**Comment by vivianjeng** [comment]
> So should I move this circuit file to Unirep Social repo?

yes I think so

**Comment by yuriko627** [comment]
Made a new PR here! https://github.com/Unirep/Unirep-Social/pull/153

**Pull request closed without merging**
